version: '3'

services:
  stac-compose:
    build: ./
    container_name: stac-compose
    ports:
      - "5050:5000"
    restart: always
    networks:
      - stac-compose-network

networks:
  stac-compose-network:
    driver: bridge

